version: '3.1'
services:
  node:
    container_name: league-master-app
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27018'